### ISSUE TITLE
.breadboard is not a directory error on import (Windows 10/JDK8)

### ISSUE THREAD

**Issue by wyattis** [human-nature-lab/breadboard#132]
```
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: java.io.IOException: Source 'experiments\Full Text Message_33_1517330905\.breadboard' is not a directory
[error] application -

! @76nkh7fje - Internal server error, for (POST) [/experiment/import/Full%20Text%20Message] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.io.IOException: Source 'experiments\Full Text Message_33_1517330905\.breadboard' is not a directory]]
        at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
Caused by: java.lang.RuntimeException: java.io.IOException: Source 'experiments\Full Text Message_33_1517330905\.breadboard' is not a directory
        at play.mvc.Security$AuthenticatedAction.call(Security.java:53) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278) [org.scala-lang.scala-library-2.10.2.jar:na]
Caused by: java.io.IOException: Source 'experiments\Full Text Message_33_1517330905\.breadboard' is not a directory
        at org.apache.commons.io.FileUtils.moveDirectory(FileUtils.java:2574) ~[commons-io.commons-io-2.3.jar:2.3]
        at controllers.ExperimentController.importExperiment(ExperimentController.java:149) ~[breadboard.breadboard-v2.3.0.jar:2.2.0]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$36$$anonfun$apply$36.apply(routes_routing.scala:526) ~[breadboard.breadboard-v2.3.0.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$36$$anonfun$apply$36.apply(routes_routing.scala:526) ~[breadboard.breadboard-v2.3.0.jar:na]
        at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
```

**Comment by wyattis** [comment]
```
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: java.io.IOException: Source 'experiments\Pirate game (no version)_34_1517331085\client-graph.js' is not a directory
[error] application -

! @76nkhhlh4 - Internal server error, for (POST) [/experiment/import/Pirate%20game%20(no%20version)] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.io.IOException: Source 'experiments\Pirate game (no version)_34_1517331085\client-graph.js' is not a directory]]
        at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
Caused by: java.lang.RuntimeException: java.io.IOException: Source 'experiments\Pirate game (no version)_34_1517331085\client-graph.js' is not a directory
        at play.mvc.Security$AuthenticatedAction.call(Security.java:53) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278) [org.scala-lang.scala-library-2.10.2.jar:na]
Caused by: java.io.IOException: Source 'experiments\Pirate game (no version)_34_1517331085\client-graph.js' is not a directory
        at org.apache.commons.io.FileUtils.moveDirectory(FileUtils.java:2574) ~[commons-io.commons-io-2.3.jar:2.3]
        at controllers.ExperimentController.importExperiment(ExperimentController.java:149) ~[breadboard.breadboard-v2.3.0.jar:2.2.0]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$36$$anonfun$apply$36.apply(routes_routing.scala:526) ~[breadboard.breadboard-v2.3.0.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$36$$anonfun$apply$36.apply(routes_routing.scala:526) ~[breadboard.breadboard-v2.3.0.jar:na]
        at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
        at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
```
Appears to be unrelated to .breadboard file and is just an issue with reading files on import.
