### ISSUE TITLE
PersistenceException on saving style for newly created experiment

### ISSUE THREAD

**Issue by disperse** [human-nature-lab/breadboard#154]
! @7701ap5nl - Internal server error, for (POST) [/customize/style/2] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Error loading on models.Experiment.style]]
	at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
	at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.2.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.0.jar:2.2.0]
Caused by: javax.persistence.PersistenceException: Error loading on models.Experiment.style
	at com.avaje.ebeaninternal.server.query.SqlBeanLoad.load(SqlBeanLoad.java:113) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.load(BeanProperty.java:587) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.query.SqlTreeNodeBean.load(SqlTreeNodeBean.java:257) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.readRow(CQuery.java:497) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.readBeanInternal(CQuery.java:531) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.hasNextBean(CQuery.java:658) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: org.h2.jdbc.JdbcSQLException: IO Exception: ""Missing lob: 36"" [90028-172]"; "lob: null table: -1 id: 36" [90031-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:158) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.convertIOException(DbException.java:315) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.value.ValueLobDb.getInputStream(ValueLobDb.java:316) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.value.ValueLobDb.getReader(ValueLobDb.java:299) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.value.ValueLobDb.getString(ValueLobDb.java:214) ~[com.h2database.h2-1.3.172.jar:1.3.172]
Caused by: java.io.IOException: org.h2.jdbc.JdbcSQLException: IO Exception: "Missing lob: 36" [90028-172]
	at org.h2.message.DbException.convertToIOException(DbException.java:348) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.store.LobStorageBackend.getInputStream(LobStorageBackend.java:326) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.value.ValueLobDb.getInputStream(ValueLobDb.java:314) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.value.ValueLobDb.getReader(ValueLobDb.java:299) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.value.ValueLobDb.getString(ValueLobDb.java:214) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:279) ~[com.h2database.h2-1.3.172.jar:1.3.172]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "Missing lob: 36" [90028-172]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:169) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.message.DbException.get(DbException.java:146) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.store.LobStorageBackend.getInputStream(LobStorageBackend.java:321) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.value.ValueLobDb.getInputStream(ValueLobDb.java:314) ~[com.h2database.h2-1.3.172.jar:1.3.172]
	at org.h2.value.ValueLobDb.getReader(ValueLobDb.java:299) ~[com.h2database.h2-1.3.172.jar:1.3.172]

**Comment by disperse** [comment]
Can't reproduce, seems like one of those flaky ebean issues that self resolved on the next try. Eventual fix will be getting rid of all the automatic getters and setters and using JDBC or JPA.

**Comment by disperse** [comment]
Reopen if we can come up with a repro case
