### ISSUE TITLE
Importing experiment after deleting same experiment fails

### ISSUE THREAD

**Issue by wyattis** [human-nature-lab/breadboard#55]
```
[debug] application - ImportExperiment
[debug] application - breadboardMessage.getClass().getName() = models.Breadboard$ImportExperiment
[debug] application - Importing experiment from ugur-dennis-experiment-17-11-15 to ugur-dennis
[debug] application - Adding step: AddTiesStep
[debug] application - Adding step: CooperationStep
[debug] application - Adding step: CutTiesStep
[debug] application - Adding step: DropPlayerStep
[debug] application - Adding step: FinishStep
[debug] application - Adding step: InitStep
[debug] application - Adding step: OnJoinStep
[debug] application - Adding step: OnLeaveStep
[debug] application - Adding step: ReadInWordsStep
[debug] application - Adding step: RecordCoopStep
[debug] application - Adding step: RecordSurveyStep
[debug] application - Adding step: ResultsStep
[debug] application - Adding step: SurveyStep

[application-akka.actor.default-dispatcher-5] [akka://application/user/$a]  Unique expecting 0 or 1 rows but got [11]
javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [11]
        at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1236)
        at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:903)
        at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(DefaultExpressionList.java:193)
        at models.Breadboard.onReceive(Breadboard.java:539)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by wyattis** [comment]
The import process has changed completely so this bug is likely irrelevant.
